// Generated by ffigen from maplibre_native_c.h. Do not edit by hand.
// Regenerate: fvm dart run ffigen --config ffigen.yaml

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for maplibre_native_c. Generated; do not edit.
/// Regenerate: fvm dart run ffigen --config ffigen.yaml
///
class MaplibreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MaplibreBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  MaplibreBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int mln_c_version() {
    return _mln_c_version();
  }

  late final _mln_c_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>('mln_c_version');
  late final _mln_c_version = _mln_c_versionPtr.asFunction<int Function()>();

  int mln_supported_render_backend_mask() {
    return _mln_supported_render_backend_mask();
  }

  late final _mln_supported_render_backend_maskPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'mln_supported_render_backend_mask',
      );
  late final _mln_supported_render_backend_mask =
      _mln_supported_render_backend_maskPtr.asFunction<int Function()>();

  int mln_network_status_get(ffi.Pointer<ffi.Uint32> out_status) {
    return _mln_network_status_get(out_status);
  }

  late final _mln_network_status_getPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Uint32>)>>(
        'mln_network_status_get',
      );
  late final _mln_network_status_get = _mln_network_status_getPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint32>)>();

  int mln_network_status_set(int status) {
    return _mln_network_status_set(status);
  }

  late final _mln_network_status_setPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Uint32)>>(
        'mln_network_status_set',
      );
  late final _mln_network_status_set = _mln_network_status_setPtr
      .asFunction<int Function(int)>();

  mln_runtime_options mln_runtime_options_default() {
    return _mln_runtime_options_default();
  }

  late final _mln_runtime_options_defaultPtr =
      _lookup<ffi.NativeFunction<mln_runtime_options Function()>>(
        'mln_runtime_options_default',
      );
  late final _mln_runtime_options_default = _mln_runtime_options_defaultPtr
      .asFunction<mln_runtime_options Function()>();

  int mln_runtime_create(
    ffi.Pointer<mln_runtime_options> options,
    ffi.Pointer<ffi.Pointer<mln_runtime>> out_runtime,
  ) {
    return _mln_runtime_create(options, out_runtime);
  }

  late final _mln_runtime_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime_options>,
            ffi.Pointer<ffi.Pointer<mln_runtime>>,
          )
        >
      >('mln_runtime_create');
  late final _mln_runtime_create = _mln_runtime_createPtr
      .asFunction<
        int Function(
          ffi.Pointer<mln_runtime_options>,
          ffi.Pointer<ffi.Pointer<mln_runtime>>,
        )
      >();

  int mln_runtime_run_ambient_cache_operation_start(
    ffi.Pointer<mln_runtime> runtime,
    int operation,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_run_ambient_cache_operation_start(
      runtime,
      operation,
      out_operation_id,
    );
  }

  late final _mln_runtime_run_ambient_cache_operation_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            ffi.Uint32,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_run_ambient_cache_operation_start');
  late final _mln_runtime_run_ambient_cache_operation_start =
      _mln_runtime_run_ambient_cache_operation_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_operation_discard(
    ffi.Pointer<mln_runtime> runtime,
    int operation_id,
  ) {
    return _mln_runtime_offline_operation_discard(runtime, operation_id);
  }

  late final _mln_runtime_offline_operation_discardPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<mln_runtime>, mln_offline_operation_id)
        >
      >('mln_runtime_offline_operation_discard');
  late final _mln_runtime_offline_operation_discard =
      _mln_runtime_offline_operation_discardPtr
          .asFunction<int Function(ffi.Pointer<mln_runtime>, int)>();

  int mln_runtime_destroy(ffi.Pointer<mln_runtime> runtime) {
    return _mln_runtime_destroy(runtime);
  }

  late final _mln_runtime_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<mln_runtime>)>>(
        'mln_runtime_destroy',
      );
  late final _mln_runtime_destroy = _mln_runtime_destroyPtr
      .asFunction<int Function(ffi.Pointer<mln_runtime>)>();

  int mln_runtime_run_once(ffi.Pointer<mln_runtime> runtime) {
    return _mln_runtime_run_once(runtime);
  }

  late final _mln_runtime_run_oncePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<mln_runtime>)>>(
        'mln_runtime_run_once',
      );
  late final _mln_runtime_run_once = _mln_runtime_run_oncePtr
      .asFunction<int Function(ffi.Pointer<mln_runtime>)>();

  int mln_runtime_poll_event(
    ffi.Pointer<mln_runtime> runtime,
    ffi.Pointer<mln_runtime_event> out_event,
    ffi.Pointer<ffi.Bool> out_has_event,
  ) {
    return _mln_runtime_poll_event(runtime, out_event, out_has_event);
  }

  late final _mln_runtime_poll_eventPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            ffi.Pointer<mln_runtime_event>,
            ffi.Pointer<ffi.Bool>,
          )
        >
      >('mln_runtime_poll_event');
  late final _mln_runtime_poll_event = _mln_runtime_poll_eventPtr
      .asFunction<
        int Function(
          ffi.Pointer<mln_runtime>,
          ffi.Pointer<mln_runtime_event>,
          ffi.Pointer<ffi.Bool>,
        )
      >();

  int mln_runtime_offline_region_create_start(
    ffi.Pointer<mln_runtime> runtime,
    ffi.Pointer<mln_offline_region_definition> definition,
    ffi.Pointer<ffi.Uint8> metadata,
    int metadata_size,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_create_start(
      runtime,
      definition,
      metadata,
      metadata_size,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_create_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            ffi.Pointer<mln_offline_region_definition>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_create_start');
  late final _mln_runtime_offline_region_create_start =
      _mln_runtime_offline_region_create_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              ffi.Pointer<mln_offline_region_definition>,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_get_start(
    ffi.Pointer<mln_runtime> runtime,
    int region_id,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_get_start(
      runtime,
      region_id,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_get_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_region_id,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_get_start');
  late final _mln_runtime_offline_region_get_start =
      _mln_runtime_offline_region_get_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_regions_list_start(
    ffi.Pointer<mln_runtime> runtime,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_regions_list_start(runtime, out_operation_id);
  }

  late final _mln_runtime_offline_regions_list_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_regions_list_start');
  late final _mln_runtime_offline_regions_list_start =
      _mln_runtime_offline_regions_list_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_update_metadata_start(
    ffi.Pointer<mln_runtime> runtime,
    int region_id,
    ffi.Pointer<ffi.Uint8> metadata,
    int metadata_size,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_update_metadata_start(
      runtime,
      region_id,
      metadata,
      metadata_size,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_update_metadata_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_region_id,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_update_metadata_start');
  late final _mln_runtime_offline_region_update_metadata_start =
      _mln_runtime_offline_region_update_metadata_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_get_status_start(
    ffi.Pointer<mln_runtime> runtime,
    int region_id,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_get_status_start(
      runtime,
      region_id,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_get_status_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_region_id,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_get_status_start');
  late final _mln_runtime_offline_region_get_status_start =
      _mln_runtime_offline_region_get_status_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_set_observed_start(
    ffi.Pointer<mln_runtime> runtime,
    int region_id,
    bool observed,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_set_observed_start(
      runtime,
      region_id,
      observed,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_set_observed_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_region_id,
            ffi.Bool,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_set_observed_start');
  late final _mln_runtime_offline_region_set_observed_start =
      _mln_runtime_offline_region_set_observed_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              bool,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_set_download_state_start(
    ffi.Pointer<mln_runtime> runtime,
    int region_id,
    int state,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_set_download_state_start(
      runtime,
      region_id,
      state,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_set_download_state_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_region_id,
            ffi.Uint32,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_set_download_state_start');
  late final _mln_runtime_offline_region_set_download_state_start =
      _mln_runtime_offline_region_set_download_state_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_invalidate_start(
    ffi.Pointer<mln_runtime> runtime,
    int region_id,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_invalidate_start(
      runtime,
      region_id,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_invalidate_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_region_id,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_invalidate_start');
  late final _mln_runtime_offline_region_invalidate_start =
      _mln_runtime_offline_region_invalidate_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_delete_start(
    ffi.Pointer<mln_runtime> runtime,
    int region_id,
    ffi.Pointer<mln_offline_operation_id> out_operation_id,
  ) {
    return _mln_runtime_offline_region_delete_start(
      runtime,
      region_id,
      out_operation_id,
    );
  }

  late final _mln_runtime_offline_region_delete_startPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_region_id,
            ffi.Pointer<mln_offline_operation_id>,
          )
        >
      >('mln_runtime_offline_region_delete_start');
  late final _mln_runtime_offline_region_delete_start =
      _mln_runtime_offline_region_delete_startPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<mln_offline_operation_id>,
            )
          >();

  int mln_runtime_offline_region_create_take_result(
    ffi.Pointer<mln_runtime> runtime,
    int operation_id,
    ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>> out_region,
  ) {
    return _mln_runtime_offline_region_create_take_result(
      runtime,
      operation_id,
      out_region,
    );
  }

  late final _mln_runtime_offline_region_create_take_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_operation_id,
            ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>>,
          )
        >
      >('mln_runtime_offline_region_create_take_result');
  late final _mln_runtime_offline_region_create_take_result =
      _mln_runtime_offline_region_create_take_resultPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>>,
            )
          >();

  int mln_runtime_offline_region_get_take_result(
    ffi.Pointer<mln_runtime> runtime,
    int operation_id,
    ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>> out_region,
    ffi.Pointer<ffi.Bool> out_found,
  ) {
    return _mln_runtime_offline_region_get_take_result(
      runtime,
      operation_id,
      out_region,
      out_found,
    );
  }

  late final _mln_runtime_offline_region_get_take_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_operation_id,
            ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>>,
            ffi.Pointer<ffi.Bool>,
          )
        >
      >('mln_runtime_offline_region_get_take_result');
  late final _mln_runtime_offline_region_get_take_result =
      _mln_runtime_offline_region_get_take_resultPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>>,
              ffi.Pointer<ffi.Bool>,
            )
          >();

  int mln_runtime_offline_regions_list_take_result(
    ffi.Pointer<mln_runtime> runtime,
    int operation_id,
    ffi.Pointer<ffi.Pointer<mln_offline_region_list>> out_regions,
  ) {
    return _mln_runtime_offline_regions_list_take_result(
      runtime,
      operation_id,
      out_regions,
    );
  }

  late final _mln_runtime_offline_regions_list_take_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_operation_id,
            ffi.Pointer<ffi.Pointer<mln_offline_region_list>>,
          )
        >
      >('mln_runtime_offline_regions_list_take_result');
  late final _mln_runtime_offline_regions_list_take_result =
      _mln_runtime_offline_regions_list_take_resultPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<ffi.Pointer<mln_offline_region_list>>,
            )
          >();

  int mln_runtime_offline_region_update_metadata_take_result(
    ffi.Pointer<mln_runtime> runtime,
    int operation_id,
    ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>> out_region,
  ) {
    return _mln_runtime_offline_region_update_metadata_take_result(
      runtime,
      operation_id,
      out_region,
    );
  }

  late final _mln_runtime_offline_region_update_metadata_take_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_operation_id,
            ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>>,
          )
        >
      >('mln_runtime_offline_region_update_metadata_take_result');
  late final _mln_runtime_offline_region_update_metadata_take_result =
      _mln_runtime_offline_region_update_metadata_take_resultPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<ffi.Pointer<mln_offline_region_snapshot>>,
            )
          >();

  int mln_runtime_offline_region_get_status_take_result(
    ffi.Pointer<mln_runtime> runtime,
    int operation_id,
    ffi.Pointer<mln_offline_region_status> out_status,
  ) {
    return _mln_runtime_offline_region_get_status_take_result(
      runtime,
      operation_id,
      out_status,
    );
  }

  late final _mln_runtime_offline_region_get_status_take_resultPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            mln_offline_operation_id,
            ffi.Pointer<mln_offline_region_status>,
          )
        >
      >('mln_runtime_offline_region_get_status_take_result');
  late final _mln_runtime_offline_region_get_status_take_result =
      _mln_runtime_offline_region_get_status_take_resultPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_runtime>,
              int,
              ffi.Pointer<mln_offline_region_status>,
            )
          >();

  int mln_offline_region_snapshot_get(
    ffi.Pointer<mln_offline_region_snapshot> snapshot,
    ffi.Pointer<mln_offline_region_info> out_info,
  ) {
    return _mln_offline_region_snapshot_get(snapshot, out_info);
  }

  late final _mln_offline_region_snapshot_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_offline_region_snapshot>,
            ffi.Pointer<mln_offline_region_info>,
          )
        >
      >('mln_offline_region_snapshot_get');
  late final _mln_offline_region_snapshot_get =
      _mln_offline_region_snapshot_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_offline_region_snapshot>,
              ffi.Pointer<mln_offline_region_info>,
            )
          >();

  void mln_offline_region_snapshot_destroy(
    ffi.Pointer<mln_offline_region_snapshot> snapshot,
  ) {
    return _mln_offline_region_snapshot_destroy(snapshot);
  }

  late final _mln_offline_region_snapshot_destroyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<mln_offline_region_snapshot>)
        >
      >('mln_offline_region_snapshot_destroy');
  late final _mln_offline_region_snapshot_destroy =
      _mln_offline_region_snapshot_destroyPtr
          .asFunction<
            void Function(ffi.Pointer<mln_offline_region_snapshot>)
          >();

  int mln_offline_region_list_count(
    ffi.Pointer<mln_offline_region_list> list,
    ffi.Pointer<ffi.Size> out_count,
  ) {
    return _mln_offline_region_list_count(list, out_count);
  }

  late final _mln_offline_region_list_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_offline_region_list>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('mln_offline_region_list_count');
  late final _mln_offline_region_list_count = _mln_offline_region_list_countPtr
      .asFunction<
        int Function(
          ffi.Pointer<mln_offline_region_list>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int mln_offline_region_list_get(
    ffi.Pointer<mln_offline_region_list> list,
    int index,
    ffi.Pointer<mln_offline_region_info> out_info,
  ) {
    return _mln_offline_region_list_get(list, index, out_info);
  }

  late final _mln_offline_region_list_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_offline_region_list>,
            ffi.Size,
            ffi.Pointer<mln_offline_region_info>,
          )
        >
      >('mln_offline_region_list_get');
  late final _mln_offline_region_list_get = _mln_offline_region_list_getPtr
      .asFunction<
        int Function(
          ffi.Pointer<mln_offline_region_list>,
          int,
          ffi.Pointer<mln_offline_region_info>,
        )
      >();

  void mln_offline_region_list_destroy(
    ffi.Pointer<mln_offline_region_list> list,
  ) {
    return _mln_offline_region_list_destroy(list);
  }

  late final _mln_offline_region_list_destroyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<mln_offline_region_list>)
        >
      >('mln_offline_region_list_destroy');
  late final _mln_offline_region_list_destroy =
      _mln_offline_region_list_destroyPtr
          .asFunction<void Function(ffi.Pointer<mln_offline_region_list>)>();

  mln_map_options mln_map_options_default() {
    return _mln_map_options_default();
  }

  late final _mln_map_options_defaultPtr =
      _lookup<ffi.NativeFunction<mln_map_options Function()>>(
        'mln_map_options_default',
      );
  late final _mln_map_options_default = _mln_map_options_defaultPtr
      .asFunction<mln_map_options Function()>();

  int mln_map_create(
    ffi.Pointer<mln_runtime> runtime,
    ffi.Pointer<mln_map_options> options,
    ffi.Pointer<ffi.Pointer<mln_map>> out_map,
  ) {
    return _mln_map_create(runtime, options, out_map);
  }

  late final _mln_map_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_runtime>,
            ffi.Pointer<mln_map_options>,
            ffi.Pointer<ffi.Pointer<mln_map>>,
          )
        >
      >('mln_map_create');
  late final _mln_map_create = _mln_map_createPtr
      .asFunction<
        int Function(
          ffi.Pointer<mln_runtime>,
          ffi.Pointer<mln_map_options>,
          ffi.Pointer<ffi.Pointer<mln_map>>,
        )
      >();

  int mln_map_request_repaint(ffi.Pointer<mln_map> map) {
    return _mln_map_request_repaint(map);
  }

  late final _mln_map_request_repaintPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<mln_map>)>>(
        'mln_map_request_repaint',
      );
  late final _mln_map_request_repaint = _mln_map_request_repaintPtr
      .asFunction<int Function(ffi.Pointer<mln_map>)>();

  int mln_map_destroy(ffi.Pointer<mln_map> map) {
    return _mln_map_destroy(map);
  }

  late final _mln_map_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<mln_map>)>>(
        'mln_map_destroy',
      );
  late final _mln_map_destroy = _mln_map_destroyPtr
      .asFunction<int Function(ffi.Pointer<mln_map>)>();

  int mln_map_set_style_url(
    ffi.Pointer<mln_map> map,
    ffi.Pointer<ffi.Char> url,
  ) {
    return _mln_map_set_style_url(map, url);
  }

  late final _mln_map_set_style_urlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<mln_map>, ffi.Pointer<ffi.Char>)
        >
      >('mln_map_set_style_url');
  late final _mln_map_set_style_url = _mln_map_set_style_urlPtr
      .asFunction<int Function(ffi.Pointer<mln_map>, ffi.Pointer<ffi.Char>)>();

  mln_camera_options mln_camera_options_default() {
    return _mln_camera_options_default();
  }

  late final _mln_camera_options_defaultPtr =
      _lookup<ffi.NativeFunction<mln_camera_options Function()>>(
        'mln_camera_options_default',
      );
  late final _mln_camera_options_default = _mln_camera_options_defaultPtr
      .asFunction<mln_camera_options Function()>();

  int mln_map_jump_to(
    ffi.Pointer<mln_map> map,
    ffi.Pointer<mln_camera_options> camera,
  ) {
    return _mln_map_jump_to(map, camera);
  }

  late final _mln_map_jump_toPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_map>,
            ffi.Pointer<mln_camera_options>,
          )
        >
      >('mln_map_jump_to');
  late final _mln_map_jump_to = _mln_map_jump_toPtr
      .asFunction<
        int Function(ffi.Pointer<mln_map>, ffi.Pointer<mln_camera_options>)
      >();

  int mln_render_session_render_update(
    ffi.Pointer<mln_render_session> session,
  ) {
    return _mln_render_session_render_update(session);
  }

  late final _mln_render_session_render_updatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<mln_render_session>)>
      >('mln_render_session_render_update');
  late final _mln_render_session_render_update =
      _mln_render_session_render_updatePtr
          .asFunction<int Function(ffi.Pointer<mln_render_session>)>();

  int mln_render_session_destroy(ffi.Pointer<mln_render_session> session) {
    return _mln_render_session_destroy(session);
  }

  late final _mln_render_session_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<mln_render_session>)>
      >('mln_render_session_destroy');
  late final _mln_render_session_destroy = _mln_render_session_destroyPtr
      .asFunction<int Function(ffi.Pointer<mln_render_session>)>();

  int mln_render_session_clear_data(ffi.Pointer<mln_render_session> session) {
    return _mln_render_session_clear_data(session);
  }

  late final _mln_render_session_clear_dataPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<mln_render_session>)>
      >('mln_render_session_clear_data');
  late final _mln_render_session_clear_data = _mln_render_session_clear_dataPtr
      .asFunction<int Function(ffi.Pointer<mln_render_session>)>();

  mln_metal_borrowed_texture_descriptor
  mln_metal_borrowed_texture_descriptor_default() {
    return _mln_metal_borrowed_texture_descriptor_default();
  }

  late final _mln_metal_borrowed_texture_descriptor_defaultPtr =
      _lookup<
        ffi.NativeFunction<mln_metal_borrowed_texture_descriptor Function()>
      >('mln_metal_borrowed_texture_descriptor_default');
  late final _mln_metal_borrowed_texture_descriptor_default =
      _mln_metal_borrowed_texture_descriptor_defaultPtr
          .asFunction<mln_metal_borrowed_texture_descriptor Function()>();

  int mln_metal_borrowed_texture_attach(
    ffi.Pointer<mln_map> map,
    ffi.Pointer<mln_metal_borrowed_texture_descriptor> descriptor,
    ffi.Pointer<ffi.Pointer<mln_render_session>> out_session,
  ) {
    return _mln_metal_borrowed_texture_attach(map, descriptor, out_session);
  }

  late final _mln_metal_borrowed_texture_attachPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<mln_map>,
            ffi.Pointer<mln_metal_borrowed_texture_descriptor>,
            ffi.Pointer<ffi.Pointer<mln_render_session>>,
          )
        >
      >('mln_metal_borrowed_texture_attach');
  late final _mln_metal_borrowed_texture_attach =
      _mln_metal_borrowed_texture_attachPtr
          .asFunction<
            int Function(
              ffi.Pointer<mln_map>,
              ffi.Pointer<mln_metal_borrowed_texture_descriptor>,
              ffi.Pointer<ffi.Pointer<mln_render_session>>,
            )
          >();
}

abstract class mln_status {
  static const MLN_STATUS_OK = 0;
  static const MLN_STATUS_INVALID_ARGUMENT = -1;
  static const MLN_STATUS_INVALID_STATE = -2;
  static const MLN_STATUS_WRONG_THREAD = -3;
  static const MLN_STATUS_UNSUPPORTED = -4;
  static const MLN_STATUS_NATIVE_ERROR = -5;
}

abstract class mln_render_backend_flag {
  static const MLN_RENDER_BACKEND_FLAG_METAL = 1;
  static const MLN_RENDER_BACKEND_FLAG_VULKAN = 2;
  static const MLN_RENDER_BACKEND_FLAG_OPENGL = 4;
}

final class mln_runtime extends ffi.Opaque {}

final class mln_map extends ffi.Opaque {}

final class mln_map_projection extends ffi.Opaque {}

final class mln_offline_region_snapshot extends ffi.Opaque {}

final class mln_offline_region_list extends ffi.Opaque {}

final class mln_json_snapshot extends ffi.Opaque {}

final class mln_resource_request_handle extends ffi.Opaque {}

final class mln_render_session extends ffi.Opaque {}

abstract class mln_network_status {
  static const MLN_NETWORK_STATUS_ONLINE = 1;
  static const MLN_NETWORK_STATUS_OFFLINE = 2;
}

abstract class mln_runtime_option_flag {
  static const MLN_RUNTIME_OPTION_MAXIMUM_CACHE_SIZE = 1;
}

abstract class mln_ambient_cache_operation {
  static const MLN_AMBIENT_CACHE_OPERATION_RESET_DATABASE = 1;
  static const MLN_AMBIENT_CACHE_OPERATION_PACK_DATABASE = 2;
  static const MLN_AMBIENT_CACHE_OPERATION_INVALIDATE = 3;
  static const MLN_AMBIENT_CACHE_OPERATION_CLEAR = 4;
}

abstract class mln_offline_region_definition_type {
  static const MLN_OFFLINE_REGION_DEFINITION_TILE_PYRAMID = 1;
  static const MLN_OFFLINE_REGION_DEFINITION_GEOMETRY = 2;
}

abstract class mln_offline_region_download_state {
  static const MLN_OFFLINE_REGION_DOWNLOAD_INACTIVE = 0;
  static const MLN_OFFLINE_REGION_DOWNLOAD_ACTIVE = 1;
}

abstract class mln_offline_operation_kind {
  static const MLN_OFFLINE_OPERATION_AMBIENT_CACHE = 1;
  static const MLN_OFFLINE_OPERATION_REGION_CREATE = 2;
  static const MLN_OFFLINE_OPERATION_REGION_GET = 3;
  static const MLN_OFFLINE_OPERATION_REGIONS_LIST = 4;
  static const MLN_OFFLINE_OPERATION_REGIONS_MERGE_DATABASE = 5;
  static const MLN_OFFLINE_OPERATION_REGION_UPDATE_METADATA = 6;
  static const MLN_OFFLINE_OPERATION_REGION_GET_STATUS = 7;
  static const MLN_OFFLINE_OPERATION_REGION_SET_OBSERVED = 8;
  static const MLN_OFFLINE_OPERATION_REGION_SET_DOWNLOAD_STATE = 9;
  static const MLN_OFFLINE_OPERATION_REGION_INVALIDATE = 10;
  static const MLN_OFFLINE_OPERATION_REGION_DELETE = 11;
}

abstract class mln_offline_operation_result_kind {
  static const MLN_OFFLINE_OPERATION_RESULT_NONE = 0;
  static const MLN_OFFLINE_OPERATION_RESULT_REGION = 1;
  static const MLN_OFFLINE_OPERATION_RESULT_OPTIONAL_REGION = 2;
  static const MLN_OFFLINE_OPERATION_RESULT_REGION_LIST = 3;
  static const MLN_OFFLINE_OPERATION_RESULT_REGION_STATUS = 4;
}

final class mln_offline_region_status extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int download_state;

  @ffi.Uint64()
  external int completed_resource_count;

  @ffi.Uint64()
  external int completed_resource_size;

  @ffi.Uint64()
  external int completed_tile_count;

  @ffi.Uint64()
  external int required_tile_count;

  @ffi.Uint64()
  external int completed_tile_size;

  @ffi.Uint64()
  external int required_resource_count;

  @ffi.Bool()
  external bool required_resource_count_is_precise;

  @ffi.Bool()
  external bool complete;
}

abstract class mln_runtime_event_type {
  static const MLN_RUNTIME_EVENT_MAP_CAMERA_WILL_CHANGE = 1;
  static const MLN_RUNTIME_EVENT_MAP_CAMERA_IS_CHANGING = 2;
  static const MLN_RUNTIME_EVENT_MAP_CAMERA_DID_CHANGE = 3;
  static const MLN_RUNTIME_EVENT_MAP_STYLE_LOADED = 4;
  static const MLN_RUNTIME_EVENT_MAP_LOADING_STARTED = 5;
  static const MLN_RUNTIME_EVENT_MAP_LOADING_FINISHED = 6;
  static const MLN_RUNTIME_EVENT_MAP_LOADING_FAILED = 7;
  static const MLN_RUNTIME_EVENT_MAP_IDLE = 8;
  static const MLN_RUNTIME_EVENT_MAP_RENDER_UPDATE_AVAILABLE = 9;
  static const MLN_RUNTIME_EVENT_MAP_RENDER_ERROR = 10;
  static const MLN_RUNTIME_EVENT_MAP_STILL_IMAGE_FINISHED = 11;
  static const MLN_RUNTIME_EVENT_MAP_STILL_IMAGE_FAILED = 12;
  static const MLN_RUNTIME_EVENT_MAP_RENDER_FRAME_STARTED = 13;
  static const MLN_RUNTIME_EVENT_MAP_RENDER_FRAME_FINISHED = 14;
  static const MLN_RUNTIME_EVENT_MAP_RENDER_MAP_STARTED = 15;
  static const MLN_RUNTIME_EVENT_MAP_RENDER_MAP_FINISHED = 16;
  static const MLN_RUNTIME_EVENT_MAP_STYLE_IMAGE_MISSING = 17;
  static const MLN_RUNTIME_EVENT_MAP_TILE_ACTION = 18;
  static const MLN_RUNTIME_EVENT_OFFLINE_REGION_STATUS_CHANGED = 19;
  static const MLN_RUNTIME_EVENT_OFFLINE_REGION_RESPONSE_ERROR = 20;
  static const MLN_RUNTIME_EVENT_OFFLINE_REGION_TILE_COUNT_LIMIT_EXCEEDED = 21;
  static const MLN_RUNTIME_EVENT_OFFLINE_OPERATION_COMPLETED = 22;
}

abstract class mln_runtime_event_source_type {
  static const MLN_RUNTIME_EVENT_SOURCE_RUNTIME = 0;
  static const MLN_RUNTIME_EVENT_SOURCE_MAP = 1;
}

abstract class mln_runtime_event_payload_type {
  static const MLN_RUNTIME_EVENT_PAYLOAD_NONE = 0;
  static const MLN_RUNTIME_EVENT_PAYLOAD_RENDER_FRAME = 1;
  static const MLN_RUNTIME_EVENT_PAYLOAD_RENDER_MAP = 2;
  static const MLN_RUNTIME_EVENT_PAYLOAD_STYLE_IMAGE_MISSING = 3;
  static const MLN_RUNTIME_EVENT_PAYLOAD_TILE_ACTION = 4;
  static const MLN_RUNTIME_EVENT_PAYLOAD_OFFLINE_REGION_STATUS = 5;
  static const MLN_RUNTIME_EVENT_PAYLOAD_OFFLINE_REGION_RESPONSE_ERROR = 6;
  static const MLN_RUNTIME_EVENT_PAYLOAD_OFFLINE_REGION_TILE_COUNT_LIMIT = 7;
  static const MLN_RUNTIME_EVENT_PAYLOAD_OFFLINE_OPERATION_COMPLETED = 8;
}

abstract class mln_render_mode {
  static const MLN_RENDER_MODE_PARTIAL = 0;
  static const MLN_RENDER_MODE_FULL = 1;
}

abstract class mln_tile_operation {
  static const MLN_TILE_OPERATION_REQUESTED_FROM_CACHE = 0;
  static const MLN_TILE_OPERATION_REQUESTED_FROM_NETWORK = 1;
  static const MLN_TILE_OPERATION_LOAD_FROM_NETWORK = 2;
  static const MLN_TILE_OPERATION_LOAD_FROM_CACHE = 3;
  static const MLN_TILE_OPERATION_START_PARSE = 4;
  static const MLN_TILE_OPERATION_END_PARSE = 5;
  static const MLN_TILE_OPERATION_ERROR = 6;
  static const MLN_TILE_OPERATION_CANCELLED = 7;
  static const MLN_TILE_OPERATION_NULL = 8;
}

abstract class mln_resource_kind {
  static const MLN_RESOURCE_KIND_UNKNOWN = 0;
  static const MLN_RESOURCE_KIND_STYLE = 1;
  static const MLN_RESOURCE_KIND_SOURCE = 2;
  static const MLN_RESOURCE_KIND_TILE = 3;
  static const MLN_RESOURCE_KIND_GLYPHS = 4;
  static const MLN_RESOURCE_KIND_SPRITE_IMAGE = 5;
  static const MLN_RESOURCE_KIND_SPRITE_JSON = 6;
  static const MLN_RESOURCE_KIND_IMAGE = 7;
}

abstract class mln_resource_loading_method {
  static const MLN_RESOURCE_LOADING_METHOD_ALL = 0;
  static const MLN_RESOURCE_LOADING_METHOD_CACHE_ONLY = 1;
  static const MLN_RESOURCE_LOADING_METHOD_NETWORK_ONLY = 2;
}

abstract class mln_resource_priority {
  static const MLN_RESOURCE_PRIORITY_REGULAR = 0;
  static const MLN_RESOURCE_PRIORITY_LOW = 1;
}

abstract class mln_resource_usage {
  static const MLN_RESOURCE_USAGE_ONLINE = 0;
  static const MLN_RESOURCE_USAGE_OFFLINE = 1;
}

abstract class mln_resource_storage_policy {
  static const MLN_RESOURCE_STORAGE_POLICY_PERMANENT = 0;
  static const MLN_RESOURCE_STORAGE_POLICY_VOLATILE = 1;
}

abstract class mln_resource_response_status {
  static const MLN_RESOURCE_RESPONSE_STATUS_OK = 0;
  static const MLN_RESOURCE_RESPONSE_STATUS_ERROR = 1;
  static const MLN_RESOURCE_RESPONSE_STATUS_NO_CONTENT = 2;
  static const MLN_RESOURCE_RESPONSE_STATUS_NOT_MODIFIED = 3;
}

abstract class mln_resource_error_reason {
  static const MLN_RESOURCE_ERROR_REASON_NONE = 0;
  static const MLN_RESOURCE_ERROR_REASON_NOT_FOUND = 1;
  static const MLN_RESOURCE_ERROR_REASON_SERVER = 2;
  static const MLN_RESOURCE_ERROR_REASON_CONNECTION = 3;
  static const MLN_RESOURCE_ERROR_REASON_RATE_LIMIT = 4;
  static const MLN_RESOURCE_ERROR_REASON_OTHER = 5;
}

abstract class mln_resource_provider_decision {
  static const MLN_RESOURCE_PROVIDER_DECISION_PASS_THROUGH = 0;
  static const MLN_RESOURCE_PROVIDER_DECISION_HANDLE = 1;
}

final class mln_runtime_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int flags;

  external ffi.Pointer<ffi.Char> asset_path;

  external ffi.Pointer<ffi.Char> cache_path;

  @ffi.Uint64()
  external int maximum_cache_size;
}

final class mln_rendering_stats extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Double()
  external double encoding_time;

  @ffi.Double()
  external double rendering_time;

  @ffi.Int64()
  external int frame_count;

  @ffi.Int64()
  external int draw_call_count;

  @ffi.Int64()
  external int total_draw_call_count;
}

final class mln_runtime_event_render_frame extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int mode;

  @ffi.Bool()
  external bool needs_repaint;

  @ffi.Bool()
  external bool placement_changed;

  external mln_rendering_stats stats;
}

final class mln_runtime_event_render_map extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int mode;
}

final class mln_runtime_event_style_image_missing extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Char> image_id;

  @ffi.Size()
  external int image_id_size;
}

final class mln_tile_id extends ffi.Struct {
  @ffi.Uint32()
  external int overscaled_z;

  @ffi.Int32()
  external int wrap;

  @ffi.Uint32()
  external int canonical_z;

  @ffi.Uint32()
  external int canonical_x;

  @ffi.Uint32()
  external int canonical_y;
}

final class mln_runtime_event_tile_action extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int operation;

  external mln_tile_id tile_id;

  external ffi.Pointer<ffi.Char> source_id;

  @ffi.Size()
  external int source_id_size;
}

final class mln_runtime_event_offline_region_status extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @mln_offline_region_id()
  external int region_id;

  external mln_offline_region_status status;
}

typedef mln_offline_region_id = ffi.Int64;
typedef Dartmln_offline_region_id = int;

final class mln_runtime_event_offline_region_response_error extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @mln_offline_region_id()
  external int region_id;

  @ffi.Uint32()
  external int reason;
}

final class mln_runtime_event_offline_region_tile_count_limit
    extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @mln_offline_region_id()
  external int region_id;

  @ffi.Uint64()
  external int limit;
}

final class mln_runtime_event_offline_operation_completed extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @mln_offline_operation_id()
  external int operation_id;

  @ffi.Uint32()
  external int operation_kind;

  @ffi.Uint32()
  external int result_kind;

  @ffi.Int32()
  external int result_status;

  @ffi.Bool()
  external bool found;
}

typedef mln_offline_operation_id = ffi.Uint64;
typedef Dartmln_offline_operation_id = int;

final class mln_runtime_event extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  @ffi.Uint32()
  external int source_type;

  external ffi.Pointer<ffi.Void> source;

  @ffi.Int32()
  external int code;

  @ffi.Uint32()
  external int payload_type;

  external ffi.Pointer<ffi.Void> payload;

  @ffi.Size()
  external int payload_size;

  external ffi.Pointer<ffi.Char> message;

  @ffi.Size()
  external int message_size;
}

final class mln_resource_transform_response extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Char> url;

  external ffi.Pointer<ffi.Void> context;
}

final class mln_resource_transform extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_resource_transform_callback callback;

  external ffi.Pointer<ffi.Void> user_data;
}

typedef mln_resource_transform_callback =
    ffi.Pointer<ffi.NativeFunction<mln_resource_transform_callbackFunction>>;
typedef mln_resource_transform_callbackFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Uint32 kind,
      ffi.Pointer<ffi.Char> url,
      ffi.Pointer<mln_resource_transform_response> out_response,
    );
typedef Dartmln_resource_transform_callbackFunction =
    mln_status Function(
      ffi.Pointer<ffi.Void> user_data,
      int kind,
      ffi.Pointer<ffi.Char> url,
      ffi.Pointer<mln_resource_transform_response> out_response,
    );

final class mln_resource_request extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Char> url;

  @ffi.Uint32()
  external int kind;

  @ffi.Uint32()
  external int loading_method;

  @ffi.Uint32()
  external int priority;

  @ffi.Uint32()
  external int usage;

  @ffi.Uint32()
  external int storage_policy;

  @ffi.Bool()
  external bool has_range;

  @ffi.Uint64()
  external int range_start;

  @ffi.Uint64()
  external int range_end;

  @ffi.Bool()
  external bool has_prior_modified;

  @ffi.Int64()
  external int prior_modified_unix_ms;

  @ffi.Bool()
  external bool has_prior_expires;

  @ffi.Int64()
  external int prior_expires_unix_ms;

  external ffi.Pointer<ffi.Char> prior_etag;

  external ffi.Pointer<ffi.Uint8> prior_data;

  @ffi.Size()
  external int prior_data_size;
}

final class mln_resource_response extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int status;

  @ffi.Uint32()
  external int error_reason;

  external ffi.Pointer<ffi.Uint8> bytes;

  @ffi.Size()
  external int byte_count;

  external ffi.Pointer<ffi.Char> error_message;

  @ffi.Bool()
  external bool must_revalidate;

  @ffi.Bool()
  external bool has_modified;

  @ffi.Int64()
  external int modified_unix_ms;

  @ffi.Bool()
  external bool has_expires;

  @ffi.Int64()
  external int expires_unix_ms;

  external ffi.Pointer<ffi.Char> etag;

  @ffi.Bool()
  external bool has_retry_after;

  @ffi.Int64()
  external int retry_after_unix_ms;
}

final class mln_resource_provider extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_resource_provider_callback callback;

  external ffi.Pointer<ffi.Void> user_data;
}

typedef mln_resource_provider_callback =
    ffi.Pointer<ffi.NativeFunction<mln_resource_provider_callbackFunction>>;
typedef mln_resource_provider_callbackFunction =
    ffi.Uint32 Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<mln_resource_request> request,
      ffi.Pointer<mln_resource_request_handle> handle,
    );
typedef Dartmln_resource_provider_callbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<mln_resource_request> request,
      ffi.Pointer<mln_resource_request_handle> handle,
    );

abstract class mln_camera_option_field {
  static const MLN_CAMERA_OPTION_CENTER = 1;
  static const MLN_CAMERA_OPTION_ZOOM = 2;
  static const MLN_CAMERA_OPTION_BEARING = 4;
  static const MLN_CAMERA_OPTION_PITCH = 8;
  static const MLN_CAMERA_OPTION_CENTER_ALTITUDE = 16;
  static const MLN_CAMERA_OPTION_PADDING = 32;
  static const MLN_CAMERA_OPTION_ANCHOR = 64;
  static const MLN_CAMERA_OPTION_ROLL = 128;
  static const MLN_CAMERA_OPTION_FOV = 256;
}

abstract class mln_animation_option_field {
  static const MLN_ANIMATION_OPTION_DURATION = 1;
  static const MLN_ANIMATION_OPTION_VELOCITY = 2;
  static const MLN_ANIMATION_OPTION_MIN_ZOOM = 4;
  static const MLN_ANIMATION_OPTION_EASING = 8;
}

abstract class mln_camera_fit_option_field {
  static const MLN_CAMERA_FIT_OPTION_PADDING = 1;
  static const MLN_CAMERA_FIT_OPTION_BEARING = 2;
  static const MLN_CAMERA_FIT_OPTION_PITCH = 4;
}

abstract class mln_bound_option_field {
  static const MLN_BOUND_OPTION_BOUNDS = 1;
  static const MLN_BOUND_OPTION_MIN_ZOOM = 2;
  static const MLN_BOUND_OPTION_MAX_ZOOM = 4;
  static const MLN_BOUND_OPTION_MIN_PITCH = 8;
  static const MLN_BOUND_OPTION_MAX_PITCH = 16;
}

abstract class mln_free_camera_option_field {
  static const MLN_FREE_CAMERA_OPTION_POSITION = 1;
  static const MLN_FREE_CAMERA_OPTION_ORIENTATION = 2;
}

abstract class mln_projection_mode_field {
  static const MLN_PROJECTION_MODE_AXONOMETRIC = 1;
  static const MLN_PROJECTION_MODE_X_SKEW = 2;
  static const MLN_PROJECTION_MODE_Y_SKEW = 4;
}

abstract class mln_map_debug_option {
  static const MLN_MAP_DEBUG_TILE_BORDERS = 2;
  static const MLN_MAP_DEBUG_PARSE_STATUS = 4;
  static const MLN_MAP_DEBUG_TIMESTAMPS = 8;
  static const MLN_MAP_DEBUG_COLLISION = 16;
  static const MLN_MAP_DEBUG_OVERDRAW = 32;
  static const MLN_MAP_DEBUG_STENCIL_CLIP = 64;
  static const MLN_MAP_DEBUG_DEPTH_BUFFER = 128;
}

abstract class mln_north_orientation {
  static const MLN_NORTH_ORIENTATION_UP = 0;
  static const MLN_NORTH_ORIENTATION_RIGHT = 1;
  static const MLN_NORTH_ORIENTATION_DOWN = 2;
  static const MLN_NORTH_ORIENTATION_LEFT = 3;
}

abstract class mln_constrain_mode {
  static const MLN_CONSTRAIN_MODE_NONE = 0;
  static const MLN_CONSTRAIN_MODE_HEIGHT_ONLY = 1;
  static const MLN_CONSTRAIN_MODE_WIDTH_AND_HEIGHT = 2;
  static const MLN_CONSTRAIN_MODE_SCREEN = 3;
}

abstract class mln_viewport_mode {
  static const MLN_VIEWPORT_MODE_DEFAULT = 0;
  static const MLN_VIEWPORT_MODE_FLIPPED_Y = 1;
}

abstract class mln_map_viewport_option_field {
  static const MLN_MAP_VIEWPORT_OPTION_NORTH_ORIENTATION = 1;
  static const MLN_MAP_VIEWPORT_OPTION_CONSTRAIN_MODE = 2;
  static const MLN_MAP_VIEWPORT_OPTION_VIEWPORT_MODE = 4;
  static const MLN_MAP_VIEWPORT_OPTION_FRUSTUM_OFFSET = 8;
}

abstract class mln_tile_lod_mode {
  static const MLN_TILE_LOD_MODE_DEFAULT = 0;
  static const MLN_TILE_LOD_MODE_DISTANCE = 1;
}

abstract class mln_map_tile_option_field {
  static const MLN_MAP_TILE_OPTION_PREFETCH_ZOOM_DELTA = 1;
  static const MLN_MAP_TILE_OPTION_LOD_MIN_RADIUS = 2;
  static const MLN_MAP_TILE_OPTION_LOD_SCALE = 4;
  static const MLN_MAP_TILE_OPTION_LOD_PITCH_THRESHOLD = 8;
  static const MLN_MAP_TILE_OPTION_LOD_ZOOM_SHIFT = 16;
  static const MLN_MAP_TILE_OPTION_LOD_MODE = 32;
}

abstract class mln_map_mode {
  static const MLN_MAP_MODE_CONTINUOUS = 0;
  static const MLN_MAP_MODE_STATIC = 1;
  static const MLN_MAP_MODE_TILE = 2;
}

final class mln_map_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Double()
  external double scale_factor;

  @ffi.Uint32()
  external int map_mode;
}

final class mln_screen_point extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;
}

final class mln_edge_insets extends ffi.Struct {
  @ffi.Double()
  external double top;

  @ffi.Double()
  external double left;

  @ffi.Double()
  external double bottom;

  @ffi.Double()
  external double right;
}

final class mln_camera_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  @ffi.Double()
  external double latitude;

  @ffi.Double()
  external double longitude;

  @ffi.Double()
  external double center_altitude;

  external mln_edge_insets padding;

  external mln_screen_point anchor;

  @ffi.Double()
  external double zoom;

  @ffi.Double()
  external double bearing;

  @ffi.Double()
  external double pitch;

  @ffi.Double()
  external double roll;

  @ffi.Double()
  external double field_of_view;
}

final class mln_unit_bezier extends ffi.Struct {
  @ffi.Double()
  external double x1;

  @ffi.Double()
  external double y1;

  @ffi.Double()
  external double x2;

  @ffi.Double()
  external double y2;
}

final class mln_animation_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  @ffi.Double()
  external double duration_ms;

  @ffi.Double()
  external double velocity;

  @ffi.Double()
  external double min_zoom;

  external mln_unit_bezier easing;
}

final class mln_camera_fit_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external mln_edge_insets padding;

  @ffi.Double()
  external double bearing;

  @ffi.Double()
  external double pitch;
}

final class mln_vec3 extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;

  @ffi.Double()
  external double z;
}

final class mln_quaternion extends ffi.Struct {
  @ffi.Double()
  external double x;

  @ffi.Double()
  external double y;

  @ffi.Double()
  external double z;

  @ffi.Double()
  external double w;
}

final class mln_free_camera_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external mln_vec3 position;

  external mln_quaternion orientation;
}

final class mln_lat_lng extends ffi.Struct {
  @ffi.Double()
  external double latitude;

  @ffi.Double()
  external double longitude;
}

final class mln_string_view extends ffi.Struct {
  external ffi.Pointer<ffi.Char> data;

  @ffi.Size()
  external int size;
}

final class mln_json_value extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  external UnnamedUnion1 data;
}

final class UnnamedUnion1 extends ffi.Union {
  @ffi.Bool()
  external bool bool_value;

  @ffi.Uint64()
  external int uint_value;

  @ffi.Int64()
  external int int_value;

  @ffi.Double()
  external double double_value;

  external mln_string_view string_value;

  external mln_json_array array_value;

  external mln_json_object object_value;
}

final class mln_json_array extends ffi.Struct {
  external ffi.Pointer<mln_json_value> values;

  @ffi.Size()
  external int value_count;
}

final class mln_json_object extends ffi.Struct {
  external ffi.Pointer<mln_json_member> members;

  @ffi.Size()
  external int member_count;
}

final class mln_json_member extends ffi.Struct {
  external mln_string_view key;

  external ffi.Pointer<mln_json_value> value;
}

final class mln_geometry extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  external UnnamedUnion2 data;
}

final class UnnamedUnion2 extends ffi.Union {
  external mln_lat_lng point;

  external mln_coordinate_span line_string;

  external mln_polygon_geometry polygon;

  external mln_coordinate_span multi_point;

  external mln_multi_line_geometry multi_line_string;

  external mln_multi_polygon_geometry multi_polygon;

  external mln_geometry_collection geometry_collection;
}

final class mln_coordinate_span extends ffi.Struct {
  external ffi.Pointer<mln_lat_lng> coordinates;

  @ffi.Size()
  external int coordinate_count;
}

final class mln_polygon_geometry extends ffi.Struct {
  external ffi.Pointer<mln_coordinate_span> rings;

  @ffi.Size()
  external int ring_count;
}

final class mln_multi_line_geometry extends ffi.Struct {
  external ffi.Pointer<mln_coordinate_span> lines;

  @ffi.Size()
  external int line_count;
}

final class mln_multi_polygon_geometry extends ffi.Struct {
  external ffi.Pointer<mln_polygon_geometry> polygons;

  @ffi.Size()
  external int polygon_count;
}

final class mln_geometry_collection extends ffi.Struct {
  external ffi.Pointer<mln_geometry> geometries;

  @ffi.Size()
  external int geometry_count;
}

abstract class mln_geometry_type {
  static const MLN_GEOMETRY_TYPE_EMPTY = 0;
  static const MLN_GEOMETRY_TYPE_POINT = 1;
  static const MLN_GEOMETRY_TYPE_LINE_STRING = 2;
  static const MLN_GEOMETRY_TYPE_POLYGON = 3;
  static const MLN_GEOMETRY_TYPE_MULTI_POINT = 4;
  static const MLN_GEOMETRY_TYPE_MULTI_LINE_STRING = 5;
  static const MLN_GEOMETRY_TYPE_MULTI_POLYGON = 6;
  static const MLN_GEOMETRY_TYPE_GEOMETRY_COLLECTION = 7;
}

abstract class mln_json_value_type {
  static const MLN_JSON_VALUE_TYPE_NULL = 0;
  static const MLN_JSON_VALUE_TYPE_BOOL = 1;
  static const MLN_JSON_VALUE_TYPE_UINT = 2;
  static const MLN_JSON_VALUE_TYPE_INT = 3;
  static const MLN_JSON_VALUE_TYPE_DOUBLE = 4;
  static const MLN_JSON_VALUE_TYPE_STRING = 5;
  static const MLN_JSON_VALUE_TYPE_ARRAY = 6;
  static const MLN_JSON_VALUE_TYPE_OBJECT = 7;
}

abstract class mln_feature_state_selector_field {
  static const MLN_FEATURE_STATE_SELECTOR_SOURCE_LAYER_ID = 1;
  static const MLN_FEATURE_STATE_SELECTOR_FEATURE_ID = 2;
  static const MLN_FEATURE_STATE_SELECTOR_STATE_KEY = 4;
}

final class mln_feature_state_selector extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external mln_string_view source_id;

  external mln_string_view source_layer_id;

  external mln_string_view feature_id;

  external mln_string_view state_key;
}

abstract class mln_feature_identifier_type {
  static const MLN_FEATURE_IDENTIFIER_TYPE_NULL = 0;
  static const MLN_FEATURE_IDENTIFIER_TYPE_UINT = 1;
  static const MLN_FEATURE_IDENTIFIER_TYPE_INT = 2;
  static const MLN_FEATURE_IDENTIFIER_TYPE_DOUBLE = 3;
  static const MLN_FEATURE_IDENTIFIER_TYPE_STRING = 4;
}

final class mln_feature extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<mln_geometry> geometry;

  external ffi.Pointer<mln_json_member> properties;

  @ffi.Size()
  external int property_count;

  @ffi.Uint32()
  external int identifier_type;

  external UnnamedUnion3 identifier;
}

final class UnnamedUnion3 extends ffi.Union {
  @ffi.Uint64()
  external int uint_value;

  @ffi.Int64()
  external int int_value;

  @ffi.Double()
  external double double_value;

  external mln_string_view string_value;
}

abstract class mln_geojson_type {
  static const MLN_GEOJSON_TYPE_GEOMETRY = 1;
  static const MLN_GEOJSON_TYPE_FEATURE = 2;
  static const MLN_GEOJSON_TYPE_FEATURE_COLLECTION = 3;
}

final class mln_feature_collection extends ffi.Struct {
  external ffi.Pointer<mln_feature> features;

  @ffi.Size()
  external int feature_count;
}

final class mln_geojson extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  external UnnamedUnion4 data;
}

final class UnnamedUnion4 extends ffi.Union {
  external ffi.Pointer<mln_geometry> geometry;

  external ffi.Pointer<mln_feature> feature;

  external mln_feature_collection feature_collection;
}

final class mln_lat_lng_bounds extends ffi.Struct {
  external mln_lat_lng southwest;

  external mln_lat_lng northeast;
}

final class mln_bound_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external mln_lat_lng_bounds bounds;

  @ffi.Double()
  external double min_zoom;

  @ffi.Double()
  external double max_zoom;

  @ffi.Double()
  external double min_pitch;

  @ffi.Double()
  external double max_pitch;
}

final class mln_offline_tile_pyramid_region_definition extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Char> style_url;

  external mln_lat_lng_bounds bounds;

  @ffi.Double()
  external double min_zoom;

  @ffi.Double()
  external double max_zoom;

  @ffi.Float()
  external double pixel_ratio;

  @ffi.Bool()
  external bool include_ideographs;
}

final class mln_offline_geometry_region_definition extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Char> style_url;

  external ffi.Pointer<mln_geometry> geometry;

  @ffi.Double()
  external double min_zoom;

  @ffi.Double()
  external double max_zoom;

  @ffi.Float()
  external double pixel_ratio;

  @ffi.Bool()
  external bool include_ideographs;
}

final class mln_offline_region_definition extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  external UnnamedUnion5 data;
}

final class UnnamedUnion5 extends ffi.Union {
  external mln_offline_tile_pyramid_region_definition tile_pyramid;

  external mln_offline_geometry_region_definition geometry;
}

final class mln_offline_region_info extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @mln_offline_region_id()
  external int id;

  external mln_offline_region_definition definition;

  external ffi.Pointer<ffi.Uint8> metadata;

  @ffi.Size()
  external int metadata_size;
}

final class mln_projected_meters extends ffi.Struct {
  @ffi.Double()
  external double northing;

  @ffi.Double()
  external double easting;
}

final class mln_projection_mode extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  @ffi.Bool()
  external bool axonometric;

  @ffi.Double()
  external double x_skew;

  @ffi.Double()
  external double y_skew;
}

final class mln_map_viewport_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  @ffi.Uint32()
  external int north_orientation;

  @ffi.Uint32()
  external int constrain_mode;

  @ffi.Uint32()
  external int viewport_mode;

  external mln_edge_insets frustum_offset;
}

final class mln_map_tile_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  @ffi.Uint32()
  external int prefetch_zoom_delta;

  @ffi.Double()
  external double lod_min_radius;

  @ffi.Double()
  external double lod_scale;

  @ffi.Double()
  external double lod_pitch_threshold;

  @ffi.Double()
  external double lod_zoom_shift;

  @ffi.Uint32()
  external int lod_mode;
}

abstract class mln_log_severity {
  static const MLN_LOG_SEVERITY_INFO = 1;
  static const MLN_LOG_SEVERITY_WARNING = 2;
  static const MLN_LOG_SEVERITY_ERROR = 3;
}

abstract class mln_log_severity_mask {
  static const MLN_LOG_SEVERITY_MASK_INFO = 2;
  static const MLN_LOG_SEVERITY_MASK_WARNING = 4;
  static const MLN_LOG_SEVERITY_MASK_ERROR = 8;
  static const MLN_LOG_SEVERITY_MASK_DEFAULT = 6;
  static const MLN_LOG_SEVERITY_MASK_ALL = 14;
}

abstract class mln_log_event {
  static const MLN_LOG_EVENT_GENERAL = 0;
  static const MLN_LOG_EVENT_SETUP = 1;
  static const MLN_LOG_EVENT_SHADER = 2;
  static const MLN_LOG_EVENT_PARSE_STYLE = 3;
  static const MLN_LOG_EVENT_PARSE_TILE = 4;
  static const MLN_LOG_EVENT_RENDER = 5;
  static const MLN_LOG_EVENT_STYLE = 6;
  static const MLN_LOG_EVENT_DATABASE = 7;
  static const MLN_LOG_EVENT_HTTP_REQUEST = 8;
  static const MLN_LOG_EVENT_SPRITE = 9;
  static const MLN_LOG_EVENT_IMAGE = 10;
  static const MLN_LOG_EVENT_OPENGL = 11;
  static const MLN_LOG_EVENT_JNI = 12;
  static const MLN_LOG_EVENT_ANDROID = 13;
  static const MLN_LOG_EVENT_CRASH = 14;
  static const MLN_LOG_EVENT_GLYPH = 15;
  static const MLN_LOG_EVENT_TIMING = 16;
}

final class mln_feature_query_result extends ffi.Opaque {}

final class mln_feature_extension_result extends ffi.Opaque {}

abstract class mln_rendered_query_geometry_type {
  static const MLN_RENDERED_QUERY_GEOMETRY_TYPE_POINT = 1;
  static const MLN_RENDERED_QUERY_GEOMETRY_TYPE_BOX = 2;
  static const MLN_RENDERED_QUERY_GEOMETRY_TYPE_LINE_STRING = 3;
}

final class mln_screen_box extends ffi.Struct {
  external mln_screen_point min;

  external mln_screen_point max;
}

final class mln_screen_line_string extends ffi.Struct {
  external ffi.Pointer<mln_screen_point> points;

  @ffi.Size()
  external int point_count;
}

final class mln_rendered_query_geometry extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  external UnnamedUnion6 data;
}

final class UnnamedUnion6 extends ffi.Union {
  external mln_screen_point point;

  external mln_screen_box box;

  external mln_screen_line_string line_string;
}

abstract class mln_rendered_feature_query_option_field {
  static const MLN_RENDERED_FEATURE_QUERY_OPTION_LAYER_IDS = 1;
}

final class mln_rendered_feature_query_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external ffi.Pointer<mln_string_view> layer_ids;

  @ffi.Size()
  external int layer_id_count;

  external ffi.Pointer<mln_json_value> filter;
}

abstract class mln_source_feature_query_option_field {
  static const MLN_SOURCE_FEATURE_QUERY_OPTION_SOURCE_LAYER_IDS = 1;
}

final class mln_source_feature_query_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external ffi.Pointer<mln_string_view> source_layer_ids;

  @ffi.Size()
  external int source_layer_id_count;

  external ffi.Pointer<mln_json_value> filter;
}

abstract class mln_queried_feature_field {
  static const MLN_QUERIED_FEATURE_SOURCE_ID = 1;
  static const MLN_QUERIED_FEATURE_SOURCE_LAYER_ID = 2;
  static const MLN_QUERIED_FEATURE_STATE = 4;
}

final class mln_queried_feature extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external mln_feature feature;

  external mln_string_view source_id;

  external mln_string_view source_layer_id;

  external ffi.Pointer<mln_json_value> state;
}

abstract class mln_feature_extension_result_type {
  static const MLN_FEATURE_EXTENSION_RESULT_TYPE_VALUE = 1;
  static const MLN_FEATURE_EXTENSION_RESULT_TYPE_FEATURE_COLLECTION = 2;
}

final class mln_feature_extension_result_info extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  external UnnamedUnion7 data;
}

final class UnnamedUnion7 extends ffi.Union {
  external ffi.Pointer<mln_json_value> value;

  external mln_feature_collection feature_collection;
}

final class mln_render_target_extent extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Double()
  external double scale_factor;
}

final class mln_metal_context_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Void> device;
}

final class mln_vulkan_context_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Void> instance;

  external ffi.Pointer<ffi.Void> physical_device;

  external ffi.Pointer<ffi.Void> device;

  external ffi.Pointer<ffi.Void> graphics_queue;

  @ffi.Uint32()
  external int graphics_queue_family_index;

  external ffi.Pointer<ffi.Void> get_instance_proc_addr;

  external ffi.Pointer<ffi.Void> get_device_proc_addr;
}

abstract class mln_opengl_context_provider_flag {
  static const MLN_OPENGL_CONTEXT_PROVIDER_FLAG_WGL = 1;
  static const MLN_OPENGL_CONTEXT_PROVIDER_FLAG_EGL = 2;
}

abstract class mln_opengl_context_platform {
  static const MLN_OPENGL_CONTEXT_PLATFORM_UNSPECIFIED = 0;
  static const MLN_OPENGL_CONTEXT_PLATFORM_WGL = 1;
  static const MLN_OPENGL_CONTEXT_PLATFORM_EGL = 2;
}

final class mln_wgl_context_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Void> device_context;

  external ffi.Pointer<ffi.Void> share_context;

  external ffi.Pointer<ffi.Void> get_proc_address;
}

final class mln_egl_context_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<ffi.Void> display;

  external ffi.Pointer<ffi.Void> config;

  external ffi.Pointer<ffi.Void> share_context;

  external ffi.Pointer<ffi.Void> get_proc_address;
}

final class mln_opengl_context_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int platform;

  external UnnamedUnion8 data;
}

final class UnnamedUnion8 extends ffi.Union {
  external mln_wgl_context_descriptor wgl;

  external mln_egl_context_descriptor egl;
}

final class mln_style_id_list extends ffi.Opaque {}

abstract class mln_style_source_type {
  static const MLN_STYLE_SOURCE_TYPE_UNKNOWN = 0;
  static const MLN_STYLE_SOURCE_TYPE_VECTOR = 1;
  static const MLN_STYLE_SOURCE_TYPE_RASTER = 2;
  static const MLN_STYLE_SOURCE_TYPE_RASTER_DEM = 3;
  static const MLN_STYLE_SOURCE_TYPE_GEOJSON = 4;
  static const MLN_STYLE_SOURCE_TYPE_IMAGE = 5;
  static const MLN_STYLE_SOURCE_TYPE_VIDEO = 6;
  static const MLN_STYLE_SOURCE_TYPE_ANNOTATIONS = 7;
  static const MLN_STYLE_SOURCE_TYPE_CUSTOM_VECTOR = 8;
}

abstract class mln_style_tile_source_option_field {
  static const MLN_STYLE_TILE_SOURCE_OPTION_MIN_ZOOM = 1;
  static const MLN_STYLE_TILE_SOURCE_OPTION_MAX_ZOOM = 2;
  static const MLN_STYLE_TILE_SOURCE_OPTION_ATTRIBUTION = 4;
  static const MLN_STYLE_TILE_SOURCE_OPTION_SCHEME = 8;
  static const MLN_STYLE_TILE_SOURCE_OPTION_BOUNDS = 16;
  static const MLN_STYLE_TILE_SOURCE_OPTION_TILE_SIZE = 32;
  static const MLN_STYLE_TILE_SOURCE_OPTION_VECTOR_ENCODING = 64;
  static const MLN_STYLE_TILE_SOURCE_OPTION_RASTER_ENCODING = 128;
}

abstract class mln_style_tile_scheme {
  static const MLN_STYLE_TILE_SCHEME_XYZ = 0;
  static const MLN_STYLE_TILE_SCHEME_TMS = 1;
}

abstract class mln_style_vector_tile_encoding {
  static const MLN_STYLE_VECTOR_TILE_ENCODING_MVT = 0;
  static const MLN_STYLE_VECTOR_TILE_ENCODING_MLT = 1;
}

abstract class mln_style_raster_dem_encoding {
  static const MLN_STYLE_RASTER_DEM_ENCODING_MAPBOX = 0;
  static const MLN_STYLE_RASTER_DEM_ENCODING_TERRARIUM = 1;
}

abstract class mln_custom_geometry_source_option_field {
  static const MLN_CUSTOM_GEOMETRY_SOURCE_OPTION_MIN_ZOOM = 1;
  static const MLN_CUSTOM_GEOMETRY_SOURCE_OPTION_MAX_ZOOM = 2;
  static const MLN_CUSTOM_GEOMETRY_SOURCE_OPTION_TOLERANCE = 4;
  static const MLN_CUSTOM_GEOMETRY_SOURCE_OPTION_TILE_SIZE = 8;
  static const MLN_CUSTOM_GEOMETRY_SOURCE_OPTION_BUFFER = 16;
  static const MLN_CUSTOM_GEOMETRY_SOURCE_OPTION_CLIP = 32;
  static const MLN_CUSTOM_GEOMETRY_SOURCE_OPTION_WRAP = 64;
}

abstract class mln_style_image_option_field {
  static const MLN_STYLE_IMAGE_OPTION_PIXEL_RATIO = 1;
  static const MLN_STYLE_IMAGE_OPTION_SDF = 2;
}

abstract class mln_location_indicator_image_kind {
  static const MLN_LOCATION_INDICATOR_IMAGE_KIND_TOP = 0;
  static const MLN_LOCATION_INDICATOR_IMAGE_KIND_BEARING = 1;
  static const MLN_LOCATION_INDICATOR_IMAGE_KIND_SHADOW = 2;
}

final class mln_style_source_info extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int type;

  @ffi.Size()
  external int id_size;

  @ffi.Bool()
  external bool is_volatile;

  @ffi.Bool()
  external bool has_attribution;

  @ffi.Size()
  external int attribution_size;
}

final class mln_style_tile_source_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  @ffi.Double()
  external double min_zoom;

  @ffi.Double()
  external double max_zoom;

  external mln_string_view attribution;

  @ffi.Uint32()
  external int scheme;

  external mln_lat_lng_bounds bounds;

  @ffi.Uint32()
  external int tile_size;

  @ffi.Uint32()
  external int vector_encoding;

  @ffi.Uint32()
  external int raster_encoding;
}

final class mln_canonical_tile_id extends ffi.Struct {
  @ffi.Uint32()
  external int z;

  @ffi.Uint32()
  external int x;

  @ffi.Uint32()
  external int y;
}

final class mln_custom_geometry_source_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  external mln_custom_geometry_source_tile_callback fetch_tile;

  external mln_custom_geometry_source_tile_callback cancel_tile;

  external ffi.Pointer<ffi.Void> user_data;

  @ffi.Double()
  external double min_zoom;

  @ffi.Double()
  external double max_zoom;

  @ffi.Double()
  external double tolerance;

  @ffi.Uint32()
  external int tile_size;

  @ffi.Uint32()
  external int buffer;

  @ffi.Bool()
  external bool clip;

  @ffi.Bool()
  external bool wrap;
}

typedef mln_custom_geometry_source_tile_callback =
    ffi.Pointer<
      ffi.NativeFunction<mln_custom_geometry_source_tile_callbackFunction>
    >;
typedef mln_custom_geometry_source_tile_callbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> user_data,
      mln_canonical_tile_id tile_id,
    );
typedef Dartmln_custom_geometry_source_tile_callbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> user_data,
      mln_canonical_tile_id tile_id,
    );

final class mln_premultiplied_rgba8_image extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int stride;

  external ffi.Pointer<ffi.Uint8> pixels;

  @ffi.Size()
  external int byte_length;
}

final class mln_style_image_options extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int fields;

  @ffi.Float()
  external double pixel_ratio;

  @ffi.Bool()
  external bool sdf;
}

final class mln_style_image_info extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int stride;

  @ffi.Size()
  external int byte_length;

  @ffi.Float()
  external double pixel_ratio;

  @ffi.Bool()
  external bool sdf;
}

final class mln_metal_surface_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_metal_context_descriptor context;

  external ffi.Pointer<ffi.Void> layer;
}

final class mln_vulkan_surface_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_vulkan_context_descriptor context;

  external ffi.Pointer<ffi.Void> surface;
}

final class mln_opengl_surface_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_opengl_context_descriptor context;

  external ffi.Pointer<ffi.Void> surface;
}

final class mln_metal_owned_texture_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_metal_context_descriptor context;
}

final class mln_metal_borrowed_texture_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external ffi.Pointer<ffi.Void> texture;
}

final class mln_metal_owned_texture_frame extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint64()
  external int generation;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Double()
  external double scale_factor;

  @ffi.Uint64()
  external int frame_id;

  external ffi.Pointer<ffi.Void> texture;

  external ffi.Pointer<ffi.Void> device;

  @ffi.Uint64()
  external int pixel_format;
}

final class mln_vulkan_owned_texture_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_vulkan_context_descriptor context;
}

final class mln_vulkan_borrowed_texture_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_vulkan_context_descriptor context;

  external ffi.Pointer<ffi.Void> image;

  external ffi.Pointer<ffi.Void> image_view;

  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int initial_layout;

  @ffi.Uint32()
  external int final_layout;
}

final class mln_vulkan_owned_texture_frame extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint64()
  external int generation;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Double()
  external double scale_factor;

  @ffi.Uint64()
  external int frame_id;

  external ffi.Pointer<ffi.Void> image;

  external ffi.Pointer<ffi.Void> image_view;

  external ffi.Pointer<ffi.Void> device;

  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int layout;
}

final class mln_opengl_owned_texture_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_opengl_context_descriptor context;
}

final class mln_opengl_borrowed_texture_descriptor extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  external mln_render_target_extent extent;

  external mln_opengl_context_descriptor context;

  @ffi.Uint32()
  external int texture;

  @ffi.Uint32()
  external int target;
}

final class mln_opengl_owned_texture_frame extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint64()
  external int generation;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Double()
  external double scale_factor;

  @ffi.Uint64()
  external int frame_id;

  @ffi.Uint32()
  external int texture;

  @ffi.Uint32()
  external int target;

  @ffi.Uint32()
  external int internal_format;

  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int type;
}

final class mln_texture_image_info extends ffi.Struct {
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int stride;

  @ffi.Size()
  external int byte_length;
}
